MIN_BASE_SCORE = 0.05
MIN_REQUIRED_TRADES = 10
EXPLORATION_INTERVAL = 50  # strategy selection cycles
WARMUP_SCORE = 0.5
LOW_TRADE_ALPHA = 0.5
DEFAULT_ALPHA = 0.1
RECOVERY_DAYS = 7
RECOVERY_BUMP = 0.01